workflows:
  ios-workflow-id:
    name: iOS Debug Build
    max_build_duration: 10 # maximum duration in minutes before the build is terminated
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
    scripts:
      # Define your scripts for building and testing here
      - name: Set up Flutter
        script: |
          flutter upgrade
          flutter config --enable-ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Debug
        script: |
          flutter build ios --debug --no-codesign

      # Add any other custom scripts you might need for your build

    artifacts:
      # Define the artifacts that you want to store after the build
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      # Define any publishing steps if needed
      email:
        recipients:
          - winphay.1995@gmail.com
