workflows:
  ios-workflow-id:
    name: iOS Sample Workflow
    scripts:
      name: Flutter build ipa
        script: | 
            flutter build ios --debug --no-codesign\
            --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - flutter_drive.log